import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const translations = {
  es: {
    // Nav
    menu: 'Menú',
    cart: 'Carrito',
    orders: 'Mis Pedidos',
    profile: 'Perfil',
    favorites: 'Favoritos',
    chat: 'Chat',
    admin: 'Admin',
    logout: 'Cerrar Sesión',
    login: 'Iniciar Sesión',
    signup: 'Registrarse',
    // Home
    tagline: 'Fresas con Amor, Sabor Premium',
    subtitle: 'Fresitas con crema, chocolate y más — preparadas para ti con los mejores ingredientes frescos',
    orderNow: 'Pedir Ahora',
    seeMenu: 'Ver Menú',
    open: 'Abierto',
    closed: 'Cerrado',
    featuredProducts: 'Nuestras Estrellas',
    featuredSubtitle: 'Los más amados por nuestros clientes',
    howItWorks: 'Cómo Funciona',
    step1: 'Escoge',
    step1desc: 'Elige tus fresitas favoritas del menú',
    step2: 'Personaliza',
    step2desc: 'Selecciona toppings, tamaño y extras',
    step3: 'Recibe',
    step3desc: 'Recibe en tu puerta con amor',
    happyCustomers: 'Clientes Felices',
    deliveries: 'Entregas',
    rating: 'Calificación',
    reviews: 'Reseñas',
    joinClub: 'Únete al Fresitas Club',
    clubDesc: 'Gana puntos con cada pedido y canjéalos por descuentos. ¡Hay sorpresas especiales en tu cumpleaños!',
    earnPoints: 'Gana 1 punto por cada $1',
    redeemPoints: '100 puntos = $5 de descuento',
    birthdayBonus: 'Bonus especial en tu cumpleaños',
    joinNow: 'Unirme Ahora',
    seasonalSpecials: 'Especiales de Temporada',
    // Menu
    allCategories: 'Todos',
    searchPlaceholder: 'Buscar fresitas...',
    sortBy: 'Ordenar por',
    popular: 'Más Populares',
    newest: 'Más Nuevos',
    priceLow: 'Precio: Menor a Mayor',
    priceHigh: 'Precio: Mayor a Menor',
    highestRated: 'Mejor Calificados',
    addToCart: 'Agregar',
    addToFavorites: 'Favorito',
    quickView: 'Vista Rápida',
    outOfStock: 'Agotado',
    categories: {
      fresitas_crema: 'Fresitas con Crema',
      chocolate: 'Chocolate',
      combinados: 'Combinados',
      especiales: 'Especiales',
      bebidas: 'Bebidas',
      temporada: 'Temporada'
    },
    // Cart
    myCart: 'Mi Carrito',
    emptyCart: 'Tu carrito está vacío',
    emptyCartDesc: 'Agrega unas deliciosas fresitas para comenzar',
    goToMenu: 'Ver Menú',
    promoCode: 'Código Promocional',
    apply: 'Aplicar',
    subtotal: 'Subtotal',
    deliveryFee: 'Envío',
    free: 'Gratis',
    discount: 'Descuento',
    total: 'Total',
    checkout: 'Proceder al Pago',
    freeDelivery: '¡Envío gratis en pedidos mayores a',
    // Checkout
    deliveryInfo: 'Información de Entrega',
    name: 'Nombre',
    phone: 'Teléfono',
    address: 'Dirección',
    customize: 'Personalizar',
    notes: 'Notas para el pedido',
    deliveryTime: 'Preferencia de entrega',
    payment: 'Método de Pago',
    efectivo: 'Efectivo',
    transferencia: 'Transferencia',
    tarjeta: 'Tarjeta',
    confirm: 'Confirmar Pedido',
    orderSummary: 'Resumen del Pedido',
    placeOrder: 'Realizar Pedido',
    orderPlaced: '¡Pedido Realizado!',
    trackingCode: 'Código de seguimiento',
    whatsappConfirm: 'Ver en WhatsApp',
    // Orders
    myOrders: 'Mis Pedidos',
    noOrders: 'No tienes pedidos aún',
    noOrdersDesc: '¡Haz tu primer pedido y disfruta!',
    orderStatus: {
      pending: 'Pendiente',
      confirmed: 'Confirmado',
      preparing: 'Preparando',
      on_the_way: 'En Camino',
      delivered: 'Entregado',
      cancelled: 'Cancelado'
    },
    reorder: 'Volver a Pedir',
    leaveReview: 'Dejar Reseña',
    contactSupport: 'Contactar Soporte',
    // Profile
    myProfile: 'Mi Perfil',
    editProfile: 'Editar Perfil',
    savedAddresses: 'Direcciones Guardadas',
    loyaltyPoints: 'Puntos Fresitas',
    myFavorites: 'Mis Favoritos',
    notifications: 'Notificaciones',
    preferences: 'Preferencias',
    save: 'Guardar',
    cancel: 'Cancelar',
    // Misc
    loading: 'Cargando...',
    error: 'Error',
    success: '¡Éxito!',
    addedToCart: '¡Agregado al carrito!',
    removedFromCart: 'Eliminado del carrito',
    addedToFavorites: '¡Agregado a favoritos!',
    removedFromFavorites: 'Eliminado de favoritos',
    size: 'Tamaño',
    small: 'Pequeño',
    medium: 'Mediano',
    large: 'Grande',
    toppings: 'Toppings',
    quantity: 'Cantidad',
    perUnit: 'c/u',
    mins: 'min',
    cal: 'cal',
    close: 'Cerrar',
    next: 'Siguiente',
    back: 'Atrás',
    stars: 'estrellas',
    writeReview: 'Escribe tu reseña...',
    submitReview: 'Enviar Reseña',
    send: 'Enviar',
    online: 'En línea',
    offline: 'Fuera de línea',
    typing: 'escribiendo...',
    chatGreeting: '¡Hola! Gracias por contactar Fresitas G&F. Te respondemos en menos de 30 minutos. 🍓',
    yourMessage: 'Tu mensaje...',
    noFavorites: 'No tienes favoritos aún',
    noFavoritesDesc: 'Explora el menú y guarda tus favoritos',
  },
  en: {
    menu: 'Menu',
    cart: 'Cart',
    orders: 'My Orders',
    profile: 'Profile',
    favorites: 'Favorites',
    chat: 'Chat',
    admin: 'Admin',
    logout: 'Log Out',
    login: 'Log In',
    signup: 'Sign Up',
    tagline: 'Strawberries with Love, Premium Flavor',
    subtitle: 'Fresh strawberries with cream, chocolate and more — made with the finest fresh ingredients',
    orderNow: 'Order Now',
    seeMenu: 'See Menu',
    open: 'Open',
    closed: 'Closed',
    featuredProducts: 'Our Stars',
    featuredSubtitle: 'Most loved by our customers',
    howItWorks: 'How It Works',
    step1: 'Choose',
    step1desc: 'Pick your favorite strawberry treats from the menu',
    step2: 'Customize',
    step2desc: 'Select toppings, size and extras',
    step3: 'Receive',
    step3desc: 'Get it delivered to your door with love',
    happyCustomers: 'Happy Customers',
    deliveries: 'Deliveries',
    rating: 'Rating',
    reviews: 'Reviews',
    joinClub: 'Join Fresitas Club',
    clubDesc: 'Earn points with every order and redeem them for discounts. Special birthday surprises await!',
    earnPoints: 'Earn 1 point per $1 spent',
    redeemPoints: '100 points = $5 off',
    birthdayBonus: 'Special birthday bonus',
    joinNow: 'Join Now',
    seasonalSpecials: 'Seasonal Specials',
    allCategories: 'All',
    searchPlaceholder: 'Search...',
    sortBy: 'Sort by',
    popular: 'Most Popular',
    newest: 'Newest',
    priceLow: 'Price: Low to High',
    priceHigh: 'Price: High to Low',
    highestRated: 'Highest Rated',
    addToCart: 'Add to Cart',
    addToFavorites: 'Favorite',
    quickView: 'Quick View',
    outOfStock: 'Out of Stock',
    categories: {
      fresitas_crema: 'Strawberries & Cream',
      chocolate: 'Chocolate',
      combinados: 'Combos',
      especiales: 'Specials',
      bebidas: 'Drinks',
      temporada: 'Seasonal'
    },
    myCart: 'My Cart',
    emptyCart: 'Your cart is empty',
    emptyCartDesc: 'Add some delicious strawberries to get started',
    goToMenu: 'Browse Menu',
    promoCode: 'Promo Code',
    apply: 'Apply',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery',
    free: 'Free',
    discount: 'Discount',
    total: 'Total',
    checkout: 'Proceed to Checkout',
    freeDelivery: 'Free delivery on orders over',
    deliveryInfo: 'Delivery Information',
    name: 'Name',
    phone: 'Phone',
    address: 'Address',
    customize: 'Customize',
    notes: 'Order notes',
    deliveryTime: 'Delivery preference',
    payment: 'Payment Method',
    efectivo: 'Cash',
    transferencia: 'Bank Transfer',
    tarjeta: 'Card',
    confirm: 'Confirm Order',
    orderSummary: 'Order Summary',
    placeOrder: 'Place Order',
    orderPlaced: 'Order Placed!',
    trackingCode: 'Tracking code',
    whatsappConfirm: 'View on WhatsApp',
    myOrders: 'My Orders',
    noOrders: 'No orders yet',
    noOrdersDesc: 'Place your first order and enjoy!',
    orderStatus: {
      pending: 'Pending',
      confirmed: 'Confirmed',
      preparing: 'Preparing',
      on_the_way: 'On the Way',
      delivered: 'Delivered',
      cancelled: 'Cancelled'
    },
    reorder: 'Reorder',
    leaveReview: 'Leave Review',
    contactSupport: 'Contact Support',
    myProfile: 'My Profile',
    editProfile: 'Edit Profile',
    savedAddresses: 'Saved Addresses',
    loyaltyPoints: 'Fresitas Points',
    myFavorites: 'My Favorites',
    notifications: 'Notifications',
    preferences: 'Preferences',
    save: 'Save',
    cancel: 'Cancel',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success!',
    addedToCart: 'Added to cart!',
    removedFromCart: 'Removed from cart',
    addedToFavorites: 'Added to favorites!',
    removedFromFavorites: 'Removed from favorites',
    size: 'Size',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    toppings: 'Toppings',
    quantity: 'Quantity',
    perUnit: 'ea',
    mins: 'min',
    cal: 'cal',
    close: 'Close',
    next: 'Next',
    back: 'Back',
    stars: 'stars',
    writeReview: 'Write your review...',
    submitReview: 'Submit Review',
    send: 'Send',
    online: 'Online',
    offline: 'Offline',
    typing: 'typing...',
    chatGreeting: 'Hello! Thanks for contacting Fresitas G&F. We\'ll respond within 30 minutes. 🍓',
    yourMessage: 'Your message...',
    noFavorites: 'No favorites yet',
    noFavoritesDesc: 'Explore the menu and save your favorites',
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    return localStorage.getItem('fresitas_lang') || 'es';
  });

  const toggleLanguage = () => {
    const newLang = language === 'es' ? 'en' : 'es';
    setLanguage(newLang);
    localStorage.setItem('fresitas_lang', newLang);
  };

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}